--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MewKi99/Plugin-TestUI-Minecraft-Pocketmine
build-by-default: true
branches:
- main
projects:
  Plugin-TestUI-Minecraft-Pocketmine:
    path: ""
...
